CREATE TABLE Cart (
    CartID INT PRIMARY KEY IDENTITY,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES [User](UserID)
);
GO
CREATE PROCEDURE Cart_Create
    @UserID INT
AS
BEGIN
    INSERT INTO Cart (UserID) VALUES (@UserID);
    SELECT SCOPE_IDENTITY() AS CartID;
END;
GO
CREATE PROCEDURE Cart_Read
    @CartID INT
AS
BEGIN
    SELECT * FROM Cart WHERE CartID = @CartID;
END;
GO
CREATE PROCEDURE Cart_Delete
    @CartID INT
AS
BEGIN
    DELETE FROM Cart WHERE CartID = @CartID;
END;